#!/usr/bin/env bash
#
# Seeds avatars and portfolio photos for the permanent test roster.
#
# WHY THIS EXISTS
#
# The platform had three media rows in total and five of six artists had no
# avatar, so the discovery grid rendered every artist as two initials on a
# coloured square. That is not a styling problem - a beauty marketplace where
# you cannot see any beauty work will never look like one - and it made every
# UI review of the browse surface meaningless.
#
# WHY WORK PHOTOS AND NOT FACES
#
# Deliberately NOT portraits. A stranger's photograph presented as "Rania
# Khoury, verified artist" is impersonation-shaped even in test data, and this
# platform ships a verified badge and an impersonation report category. Work
# product is also what a lot of real beauty artists use as their avatar.
#
# Images are CURATED Unsplash photo IDs, not a keyword service. The first
# attempt used loremflickr's tag search and it was unusable: "makeup" returned
# a typographic poster, "lipstick" returned a woman holding a plate of food,
# and "manicure" returned industrial machinery - because those are Flickr user
# tags, not curation. Every URL here was checked for a 200 before it was
# written down.
#
# Free to use under the Unsplash licence, hotlinked from their CDN as their
# guidelines permit. No credentials and no quota consumed - nothing is
# uploaded to the project's Cloudinary account.
#
# Idempotent: re-running replaces the same rows rather than accumulating.
# Reverse with scripts/seed-portfolio.sh --clear
set -euo pipefail

PSQL=(docker exec -i bedge-postgres psql -U postgres -d bedge)

if [[ "${1:-}" == "--clear" ]]; then
  "${PSQL[@]}" <<'SQL'
DELETE FROM media WHERE url LIKE 'https://loremflickr.com/%';
UPDATE artists SET avatar_url = NULL WHERE avatar_url LIKE 'https://loremflickr.com/%';
SQL
  echo "seed-portfolio: cleared"
  exit 0
fi

"${PSQL[@]}" <<'SQL'
-- GENERATED by scripts/seed-portfolio.sh. Curated Unsplash photo IDs, every
-- one verified to return 200 AND inspected on a contact sheet before it was
-- written here. Checking the status code was not enough: the alt text from
-- the search page is unreliable, and the only way to know an image suits a
-- nail artist is to look at it.
--
-- Avatars are chosen for legibility at 40px in a circle, which is a different
-- test from looking good in a grid: a held-open makeup palette reads as a
-- laptop at that size, so mkup1 uses an application shot instead.
WITH avatars(name, url) AS (VALUES
    ('Rania', 'https://images.unsplash.com/photo-1709477542149-f4e0e21d590b?w=600&h=600&fit=crop&q=80'),
    ('mkup1', 'https://images.unsplash.com/photo-1709477542170-f11ee7d471a0?w=600&h=600&fit=crop&q=80'),
    ('mkup2', 'https://images.unsplash.com/photo-1630084775816-7abb7383ded5?w=600&h=600&fit=crop&q=80'),
    ('mkup3', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=600&h=600&fit=crop&q=80'),
    ('mkup4', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=600&fit=crop&q=80')
)
UPDATE artists a
   SET avatar_url = v.url, updated_at = NOW()
  FROM users u, avatars v
 WHERE u.id = a.user_id AND u.name = v.name;

DELETE FROM media WHERE url LIKE 'https://images.unsplash.com/%'
                     OR url LIKE 'https://loremflickr.com/%';

INSERT INTO media (owner_type, owner_id, url, type, display_order)
SELECT 'artist', a.id, v.url, 'photo', v.ord
  FROM artists a
  JOIN users u ON u.id = a.user_id
  JOIN (VALUES
    ('Rania', 'https://images.unsplash.com/photo-1709477542149-f4e0e21d590b?w=600&h=600&fit=crop&q=80', 0),
    ('Rania', 'https://images.unsplash.com/photo-1636023730877-233b9237d4ec?w=600&h=600&fit=crop&q=80', 1),
    ('Rania', 'https://images.unsplash.com/photo-1638959882708-9503b1cd595f?w=600&h=600&fit=crop&q=80', 2),
    ('Rania', 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop&q=80', 3),
    ('Rania', 'https://images.unsplash.com/photo-1583784561105-a674080f391e?w=600&h=600&fit=crop&q=80', 4),
    ('mkup1', 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=600&h=600&fit=crop&q=80', 0),
    ('mkup1', 'https://images.unsplash.com/photo-1709477542170-f11ee7d471a0?w=600&h=600&fit=crop&q=80', 1),
    ('mkup1', 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&h=600&fit=crop&q=80', 2),
    ('mkup1', 'https://images.unsplash.com/photo-1622336889416-8d790ad807d7?w=600&h=600&fit=crop&q=80', 3),
    ('mkup2', 'https://images.unsplash.com/photo-1630084775816-7abb7383ded5?w=600&h=600&fit=crop&q=80', 0),
    ('mkup2', 'https://images.unsplash.com/photo-1613966802194-d46a163af70d?w=600&h=600&fit=crop&q=80', 1),
    ('mkup2', 'https://images.unsplash.com/photo-1571332283201-99c82a8b3046?w=600&h=600&fit=crop&q=80', 2),
    ('mkup2', 'https://images.unsplash.com/photo-1600634999623-864991678406?w=600&h=600&fit=crop&q=80', 3),
    ('mkup3', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=600&h=600&fit=crop&q=80', 0),
    ('mkup3', 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=600&h=600&fit=crop&q=80', 1),
    ('mkup3', 'https://images.unsplash.com/photo-1629397685944-7073f5589754?w=600&h=600&fit=crop&q=80', 2),
    ('mkup3', 'https://images.unsplash.com/photo-1675034743339-0b0747047727?w=600&h=600&fit=crop&q=80', 3),
    ('mkup4', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=600&fit=crop&q=80', 0),
    ('mkup4', 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600&h=600&fit=crop&q=80', 1),
    ('mkup4', 'https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?w=600&h=600&fit=crop&q=80', 2),
    ('mkup4', 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=600&h=600&fit=crop&q=80', 3)
  ) AS v(name, url, ord) ON v.name = u.name;

SELECT u.name,
       CASE WHEN a.avatar_url IS NULL THEN 'none' ELSE 'set' END AS avatar,
       (SELECT count(*) FROM media md WHERE md.owner_id = a.id AND md.owner_type = 'artist') AS photos
  FROM artists a JOIN users u ON u.id = a.user_id
 ORDER BY u.name;
SQL
echo "seed-portfolio: done"
